### ISSUE TITLE
Control with media keys

### ISSUE THREAD

**Issue by maciej-skurznica** [mendz/youtube-fast-rewind-forward-buttons#25]
Can you add an option to be able to map rewind, fast-forward to previous / next video media keys?

**Comment by mendz** [comment]
Hey @maciej-skurznica, I added this option in the new version `v1.3.0` in pull request #33.

I tested it with my own keyboard, so it may behave differently on another one. Let me know how it works for you.

Please keep in mind that it may take a few days for Chrome to start using the new version.
